### ISSUE TITLE
schema.Password + PATCH-ing resource leads to password corruption in database

### ISSUE THREAD

**Issue by markostojanovic087** [rs/rest-layer#247] opened 2019-04-28 02:34 UTC
**1. Create a resource:**
```
user = schema.Schema{
```
with fields:
```
'id':      {
	Required:    true,
	Filterable:  true,
	Sortable:    true,
	Validator: &schema.String{},
},
'password':	schema.PasswordField,
'name: {
	Required:   true,
	Filterable: true,
	Sortable: 	true,
	Validator: 	&schema.String{
		MaxLen: LEN_NAME,
	},
},
```
**2. Send a POST http request with given body to create a user in db**
```
{"id":"wa", "name":"wa", "password":"wa"}
```
NOTE: _Password is bcrypt-ed and now it is stored as 
bcrypt("wa") = $2a$10$LQ7acVly8v2Vdq1S5cHmXeKFFel5A.0Qv6Y/CukvmCfvlkogr0pD2_

**3. Send a PATCH http request with body**
```
[
  {"op": "replace", "path": "/name", "value": "newname"}
]
```
**4. Observe that the password stored gets also changed** 
and now it is
_bcrypt("$2a$10$LQ7acVly8v2Vdq1S5cHmXeKFFel5A.0Qv6Y/CukvmCfvlkogr0pD2_") = 
$2a$10$DFQyiUsTr.dAAUBi.MOvwuTOHyt.zWRCJmx/5zMtqSm1BIqWLBivy_

**CONCLUSION:**
Password is encrypted again on PATCH and so it gets corrupted.
In order to log in, the user should use previously encrypted password value as password

**Comment by Dragomir-Ivanov** [comment] 2019-04-30 23:07
The issue probably lies somewhere here in `func (s Schema) Prepare(ctx context.Context, payload map[string]interface{}, original *map[string]interface{}, replace bool)`

```
			// Apply value to change-set only if the field was not identical same in the original doc.
			if found {
				if def.Validator != nil {
					if validated, err := def.Validator.Validate(value); err != nil {
						// We treat a validation error as a change; the validation
						// error indicate invalid payload and will be caught
						// again by schema.Validate().
						changes[field] = value
					} else if !oFound || !reflect.DeepEqual(validated, oValue) {
						changes[field] = validated
					}
				} else if !oFound || !reflect.DeepEqual(value, oValue) {
					changes[field] = value
				}
```
Does calling `bcrypt.GenerateFromPassword` with the same password results with the same hash?

**Comment by smyrman** [comment] 2019-05-01 00:23
> Does calling bcrypt.GenerateFromPassword with the same password results with the same hash?

The issue is that on the second patch, the hash will be called again on the hash from the previous operation, so the hash will be hashed, even when no new password was provided.

**Comment by Dragomir-Ivanov** [comment] 2019-05-01 07:06
I think you are right @smyrman . So I guess this can be fixed if we introduce new type that can wrap the password within rest-layer. Then that type implements `FieldSerializer` so when password hash is extracted from DB is converted to the type. Then `Validate` will check, and skip if new password generation for this type. Unfortunately I don't have much time right now to look deeper.

**Comment by markostojanovic087** [comment] 2019-05-01 11:32
For others reading this I would add a workaround.

Assuming that credentials are email and password 
the workaround is: 

1. Remove password from user resource/table.

2. Create a new resource (creds) with:
- id (user email)
- password
- idUse (user id) - _Adding this is logically redundant but we need it since as much as I could see we can only get resources from storage by their id. (**can't make custom queries**) Therefore, we need to have user id in the new resource/table so we can reference user and get corresponding user._

Note: _If you use email as user id you won't have three fields in creds resource, but as much as I could see that is a problem, since you won't be able to change it. (**can't change id's**)_

@smyrman Could you plase confirm bolded drawbacks and advise if I should create a separate issues for them or that works as intended?

3.  Be sure to create a composite foreign key in your storage made from (id, idUse) referencing (email, id) from user. Also, foreign key should be with ON DELETE CASCADE ON UPDATE CASCADE, so you can change email from user table and that change is propagated to credentials table. That way we keep possibility for changing both email, password and other user information.

**Comment by smyrman** [comment] 2019-05-02 10:50
Let's discuss the first issue first, which is password hash being updated on PATCH. From what i can see on the `schema.Password` type, I think this is related to your storage backend returning the password hash as a `string` rather than `[]byte`.

The current code assumes the password to already be hashed when it is `[]byte` and not `string`.

See issue #243.

**Comment by Dragomir-Ivanov** [comment] 2019-05-02 11:01
What about:
```
func (v Password) Serialize(value interface{}) (interface{}, error) {
	if s, ok := value.(string); ok {
            return []byte(s), nil
        }
        return nil, errors.New("not a string")
}
```

**Comment by smyrman** [comment] 2019-05-02 16:37
Well, Serialize is only called when evaluating projections, so it would not help.

**Comment by smyrman** [comment] 2019-08-19 11:41
I am going to close this issue.

I view this currently as a documentation issue on the (third-party) SQL Storer backend. Feel free to raise it again there. I believe it to be fixable by altering the SQL schema to use a byre-array for storing the password.

**Closed by smyrman** 2019-08-19 11:41 UTC
Labels: SQL Storer, bug
