### ISSUE TITLE
Question - Support for multi-level resources?

### ISSUE THREAD

**Issue by atul-nagar** [rs/rest-layer#144] opened 2017-09-28 09:45 UTC
Hello,
I'm trying to create a multi-level heirarchy of resources, but am unable to get it to work beyond two top level resources. Below is the schema definition:
```
var Foundation = schema.Schema{
	Description: "Schema describing foundation",
	Fields: schema.Fields{
		"id": schema.IDField,
		"name": {
			Required:   true,
			Filterable: true,
			Sortable:   true,
			Validator:  &schema.String{},
		},
	},
}
```

```
var Org = schema.Schema{
	Description: "Schema describing Org",
	Fields: schema.Fields{
		"id": schema.IDField,
		"name": {
			Required:   true,
			Filterable: true,
			Sortable:   true,
			Validator:  &schema.String{},
		},
		"foundation": {
			Required:   true,
			Filterable: true,
			Sortable:   true,
			Validator: &schema.Reference{
				Path: "foundations",
			},
		},
	},
}

```
```
var Space = schema.Schema{
	Description: "Schema describing Space",
	Fields: schema.Fields{
		"id": schema.IDField,
		"name": {
			Required:   true,
			Filterable: true,
			Sortable:   true,
			Validator:  &schema.String{},
		},
		"org": {
			Required:   true,
			Filterable: true,
			Sortable:   true,
			Validator: &schema.Reference{
				Path: "orgs",
			},
		},
	},
}
```

And the corresponding binding:
```
foundations := index.Bind("foundations", fractal_schema.Foundation, mem.NewHandler(), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})

	orgs := foundations.Bind("orgs", "foundation", fractal_schema.Org, mem.NewHandler(), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})

	spaces := orgs.Bind("spaces", "org", fractal_schema.Space, mem.NewHandler(), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})

```
This gives me the following error:
{"time":"2017-09-28T14:59:34+05:30","level":"fatal","message":"Invalid API configuration: foundations.orgs.spaces: schema compilation error: org: can't find resource 'orgs'"}
exit status 1

Any tips would be helpful.
Thanks

**Comment by smyrman** [comment] 2017-09-28 11:41
```
Path: "orgs",
```
should be:
```
Path: "foundations.orgs",
```

**Comment by atul-nagar** [comment] 2017-09-28 12:09
thanks, does it also have an impact on how one invokes a POST operation on the leaf resource?
e.g.
```
POST  http://localhost:8080/api/foundations/<foundationid>/orgs/<orgid>/spaces
content-type: application/json

{
    "name": "space1"
}
```

fails with an error 
```
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json
Request-Id: b76ecieo4oi3792l7opg
Vary: Origin
Date: Thu, 28 Sep 2017 12:08:41 GMT
Content-Length: 93

{
  "code": 422,
  "issues": {
    "foundation": [
      "invalid field"
    ]
  },
  "message": "Document contains error(s)"
}
```

**Comment by smyrman** [comment] 2017-09-28 12:21
This is interesting. It could be a bug, or it could be intended.

I suppose it might work if you add a "foundation" filed to the outer resource, even if it duplicates link information.

**Comment by smyrman** [comment] 2017-09-28 12:22
@rs, what is the intended behaviour here?

**Comment by atul-nagar** [comment] 2017-09-28 12:24
Adding foundation field to the outer resources might be worth trying, however not what I would ideally want to do.

**Comment by rs** [comment] 2017-09-29 02:42
You need to use `foundations.orgs` as `Path` and define the `foundation` field in the `space` schema.

**Comment by rs** [comment] 2017-09-29 02:45
I agree that we should only require the parent object as a field. Please fill a bug report.

**Comment by smyrman** [comment] 2019-09-04 08:09
Closing this question now.

**Closed by smyrman** 2019-09-04 08:09 UTC
Labels: question

**Comment by Dragomir-Ivanov** [comment] 2019-09-04 08:14
I wonder if this is related to #231 / #233
